version: '2'
services:
    php:
        hostname: theater
        build: ./docker/build/php:5.6-fpm
        #build: ./docker/build/php:7-fpm
        volumes:
            - ../:/var/www
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        user: me
        links:
            - database
    # http:
    #     build: ./docker/build/httpd:2.4
    #     ports:
    #         - 81:1080
    #     volumes:
    #         - ../:/var/www
    #         - ./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    #         - ./conf/httpd/vhost-basic.conf:/usr/local/apache2/conf/extra/vhost.conf
    #         #- ./conf/httpd/vhost-symfony.conf:/usr/local/apache2/conf/extra/vhost.c
    #     user: me
    #     links:
    #        - php
    http:
        build: ./docker/build/nginx:1.8
        #build: ./docker/build/nginx:1.9
        ports:
            - 81:1080
        volumes:
            - ../:/var/www
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/vhost-basic.conf:/etc/nginx/conf.d/default.conf
            #- ./conf/nginx/vhost-symfony.conf:/etc/nginx/conf.d/default.conf
        user: me
        links:
            - php
    database:
        image: mysql:5.7
        ports:
            - 3307:3306
        # volumes:
        #     - ./database:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - 82:80
    #     links:
    #         - database
    #     environment:
    #         - PMA_HOST=database
